export const DB_MODULE = 'DATA_SOURCE';
export const COMMENT_REPOSITORY = 'COMMENT_REPOSITORY';
export const USER_REPOSITORY = 'USER_REPOSITORY';
export const UPLOAD_REPOSITORY = 'UPLOAD_REPOSITORY';
